---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false
requirements:
    requiredStorage: 12
    requiredRam: 2.0
    check: [ storage, ram, root ]
    required: [ storage, ram, root ]
