[Icon Theme]
Name=FacetUI
Comment=Glass octagons, from FacetUI
Inherits=breeze,hicolor
Directories=apps/16,apps/22,apps/24,apps/32,apps/48,apps/64,apps/128,apps/256

[apps/16]
Size=16
Context=Applications
Type=Fixed

[apps/22]
Size=22
Context=Applications
Type=Fixed

[apps/24]
Size=24
Context=Applications
Type=Fixed

[apps/32]
Size=32
Context=Applications
Type=Fixed

[apps/48]
Size=48
Context=Applications
Type=Fixed

[apps/64]
Size=64
Context=Applications
Type=Fixed

[apps/128]
Size=128
Context=Applications
Type=Fixed

[apps/256]
Size=256
Context=Applications
Type=Fixed

