#!/usr/bin/env python3
"""
Build the FacetUIIcons adaptive icon pack.

    ./make-icons.py

Produces, under FacetUIIcons/res/:

    mipmap-anydpi-v26/facetui_<glyph>.xml   adaptive icon: background,
                                            foreground, monochrome
    drawable/facetui_glyph_<glyph>.xml      the glyph, as a vector
    drawable-<dpi>/facetui_tile.png         the glass octagon, rendered from
                                            FacetUI's own shader maths
    xml/appfilter.xml                       component -> icon mapping

The glass tile is a raster because it is glass: the edge highlight and the rim
darkening are exponential falloffs, and a vector drawable has no way to express
them. The glyphs stay vectors, because a glyph is flat and should be crisp at
any size. That split is the whole design -- one shared, generated surface, with
per-app line art on top of it.

Requires Pillow and NumPy. No Android SDK.
"""

import argparse
import math
import os
import re
import sys
import xml.etree.ElementTree as ET

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "shared"))

from facetui.facet_math import edge_highlight, rim_darkening  # noqa: E402
from facetui.glyphs import APPS, GLYPHS, FALLBACK_GLYPH  # noqa: E402
# Only the two accents are still needed here, to tint the glyphs. Everything
# else the tile needs moved to shared/facetui/tile.py, which both editions
# render from.
from facetui.palette import ACCENT_A, ACCENT_B  # noqa: E402
from facetui.tile import TABLE_FRAC  # noqa: E402,F401  (re-exported)
from facetui.tile import render_tile as _render_glass  # noqa: E402
from facetui.tile import table_radius as _table_radius  # noqa: E402

#: Android's adaptive icon geometry. The drawable is 108 units square, the mask
#: covers the middle 72, and the outer 18 on each side is parallax bleed that
#: is never all visible at once.
ADAPTIVE_SIZE = 108
MASK_SIZE = 72

#: How the 100-unit glyph artwork is fitted into the 108-unit viewport.
#:
#: Not 108/100, and not the mask width either. The glyphs must clear the
#: OCTAGON, which cuts the mask's corners, and the safe zone Android documents
#: is a circle of diameter 66 in the 108 viewport -- smaller than the mask
#: square in every direction that matters.
#:
#: 0.59, arrived at twice over. First down from the mask's own 0.72 to 0.68,
#: because the widest glyph was landing at 31.7 against Android's safe radius
#: of 33 -- inside, but not by enough to survive a launcher with a tighter mask.
#: Then down again to 0.59, because fitting the MASK was never the binding
#: constraint: the glyph has to fit the TABLE, which is smaller, and measuring
#: against the mask alone had hidden that for every glyph in the pack.
#:
#: At 0.59 the widest glyph reaches 27.9 against a table edge of 30.2 and a
#: mask safe radius of 33. tools/verify-iconpack.py checks both bounds on every
#: build; the table one is the one that bites.
GLYPH_SCALE = 0.59
GLYPH_PIVOT = 50.0
GLYPH_TRANSLATE = (ADAPTIVE_SIZE - 100.0) / 2.0

#: Densities to render the tile at. The launcher picks by device density; the
#: tile is the only raster in the pack, so this is the whole of its size cost.
DENSITIES = {"mdpi": 1.0, "hdpi": 1.5, "xhdpi": 2.0, "xxhdpi": 3.0, "xxxhdpi": 4.0}
BASE_TILE_PX = 108


def table_radius():
    """Octagon-distance of the table's edge, in 108-unit viewport space.

    The boundary between the calm centre a glyph should sit on and the faceted
    crown it should not. Kept as a no-argument function because
    tools/verify-iconpack.py calls it that way; the arithmetic is shared.
    """
    return _table_radius(tile_apothem(ADAPTIVE_SIZE))


def tile_apothem(px):
    """The octagon's apothem for a `px`-wide adaptive drawable.

    The octagon fills the MASK, not the full drawable: the corners of an
    adaptive icon are parallax bleed, and a tile drawn out to them would be
    clipped to a different shape on every launcher.
    """
    return px * (MASK_SIZE / ADAPTIVE_SIZE) * 0.5


def render_tile(px):
    """The glass octagon, as an RGBA image `px` wide."""
    return _render_glass(px, tile_apothem(px))


# --- vector output ----------------------------------------------------------

VECTOR_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by iconpack/make-icons.py. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp"
    android:height="{size}dp"
    android:viewportWidth="{vp}"
    android:viewportHeight="{vp}">
    <group
        android:pivotX="{pivot}"
        android:pivotY="{pivot}"
        android:scaleX="{scale}"
        android:scaleY="{scale}"
        android:translateX="{off}"
        android:translateY="{off}">
        <path
            android:fillColor="{colour}"
            android:fillType="evenOdd"
            android:pathData="{path}" />
    </group>
</vector>
"""

ADAPTIVE_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by iconpack/make-icons.py. Do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/facetui_tile" />
    <foreground android:drawable="@drawable/facetui_glyph_{name}" />
    <monochrome android:drawable="@drawable/facetui_mono_{name}" />
</adaptive-icon>
"""


def glyph_colour(hue):
    """Glyph fill for a hue in 0..1, as #AARRGGBB.

    Lifted well above the glass beneath it. A glyph tinted the same as its own
    surface disappears the moment the specular highlight crosses it.
    """
    c = ACCENT_A * (1.0 - hue) + ACCENT_B * hue
    c = np.clip(c * 0.45 + 0.55, 0.0, 1.0)     # pull toward white
    return "#FF%02X%02X%02X" % tuple(int(round(v * 255)) for v in c)


def write_vector(path, glyph_path, colour):
    # The glyphs are authored on 0..100; an adaptive foreground is 108 with the
    # middle 72 visible. Centre the 100-unit artwork in the 108-unit viewport
    # and let the safe-zone margin the glyphs already carry do the rest.
    xml = VECTOR_TEMPLATE.format(
        size=ADAPTIVE_SIZE, vp=ADAPTIVE_SIZE,
        off=f"{GLYPH_TRANSLATE:g}", scale=f"{GLYPH_SCALE:g}",
        pivot=f"{GLYPH_PIVOT:g}",
        colour=colour, path=re.sub(r"\s+", " ", glyph_path).strip(),
    )
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(xml)


APPFILTER_HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
     Generated by iconpack/make-icons.py. Do not edit by hand.

     Component to icon mapping. A bare package matches any activity in it; a
     full ComponentInfo entry overrides its own package.

     This list is NOT the pack's coverage. Anything absent from it is themed
     procedurally by patches/iconloader/0001, which composites whatever icon
     the app ships onto the same glass. The entries here exist because a
     purpose-drawn glyph beats a wrapped one, not because the rest go untreated.
-->
<resources>
"""


def write_appfilter(path, entries):
    lines = [APPFILTER_HEADER]
    for component, name in sorted(entries):
        if "/" in component:
            comp = f"ComponentInfo{{{component}}}"
        else:
            comp = component
        lines.append(f'    <item component="{comp}" drawable="facetui_{name}" />\n')
    lines.append("</resources>\n")
    with open(path, "w", encoding="utf-8") as fh:
        fh.writelines(lines)


def main():
    ap = argparse.ArgumentParser(description="Build the FacetUIIcons pack.")
    ap.add_argument("--out", default=os.path.join(HERE, "FacetUIIcons", "res"))
    ap.add_argument("--preview", help="also write a contact sheet here")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    res = args.out
    for sub in ["drawable", "mipmap-anydpi-v26", "xml"] + \
               [f"drawable-{d}" for d in DENSITIES]:
        os.makedirs(os.path.join(res, sub), exist_ok=True)

    def note(m):
        if not args.quiet:
            print(m, file=sys.stderr)

    # --- the glass tile, once per density -----------------------------------
    note("[*] rendering the glass tile")
    for dpi, scale in DENSITIES.items():
        px = int(round(BASE_TILE_PX * scale))
        render_tile(px).save(os.path.join(res, f"drawable-{dpi}", "facetui_tile.png"))
        note(f"    {dpi:8s} {px}x{px}")

    # --- glyphs --------------------------------------------------------------
    used = sorted({g for g, _ in APPS.values()} | {FALLBACK_GLYPH})
    missing = [g for g in used if g not in GLYPHS]
    if missing:
        sys.exit(f"error: glyphs referenced but not defined: {', '.join(missing)}")

    hue_for = {}
    for glyph, hue in APPS.values():
        hue_for.setdefault(glyph, hue)
    hue_for.setdefault(FALLBACK_GLYPH, 0.5)

    note(f"[*] writing {len(used)} glyphs and adaptive icons")
    for name in used:
        write_vector(os.path.join(res, "drawable", f"facetui_glyph_{name}.xml"),
                     GLYPHS[name], glyph_colour(hue_for[name]))
        # The monochrome layer is the same artwork in a single flat colour, for
        # launchers that request it. Same path data, so the two cannot diverge.
        write_vector(os.path.join(res, "drawable", f"facetui_mono_{name}.xml"),
                     GLYPHS[name], "#FFFFFFFF")
        with open(os.path.join(res, "mipmap-anydpi-v26", f"facetui_{name}.xml"),
                  "w", encoding="utf-8") as fh:
            fh.write(ADAPTIVE_TEMPLATE.format(name=name))

    # --- appfilter -----------------------------------------------------------
    entries = [(component, glyph) for component, (glyph, _) in APPS.items()]
    write_appfilter(os.path.join(res, "xml", "appfilter.xml"), entries)
    note(f"[*] appfilter: {len(entries)} components -> {len(used)} icons")

    # --- sanity: every generated file is well-formed XML ---------------------
    bad = 0
    for dirpath, _, filenames in os.walk(res):
        for fn in filenames:
            if fn.endswith(".xml"):
                try:
                    ET.parse(os.path.join(dirpath, fn))
                except ET.ParseError as e:
                    print(f"  FAIL {fn}: {e}", file=sys.stderr)
                    bad += 1
    if bad:
        sys.exit(f"error: {bad} generated files are not well-formed")
    note("[*] all generated XML is well-formed")

    if args.preview:
        write_preview(args.preview, used, hue_for)
        note(f"[*] preview -> {args.preview}")


def write_preview(path, names, hue_for):
    """A contact sheet of every icon, composited the way a launcher would."""
    from PIL import ImageDraw
    cell = 132
    tile_px = 108
    cols = 8
    rows = (len(names) + cols - 1) // cols
    sheet = Image.new("RGBA", (cell * cols, cell * rows), (10, 12, 18, 255))
    tile = render_tile(tile_px)

    for i, name in enumerate(names):
        x = (i % cols) * cell + (cell - tile_px) // 2
        y = (i // cols) * cell + (cell - tile_px) // 2
        sheet.alpha_composite(tile, (x, y))
        glyph = rasterize_glyph(GLYPHS[name], tile_px, glyph_colour(hue_for[name]))
        sheet.alpha_composite(glyph, (x, y))

    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    sheet.convert("RGB").save(path)


def rasterize_glyph(path_data, px, colour_hex):
    """Render glyph path data, for the preview only.

    A deliberately small subset of SVG path syntax -- M, L, A, C, Z, absolute
    only -- which is all the glyphs use. Android parses the same data with its
    own full parser; this exists so the pack can be looked at without a device,
    not as a general SVG renderer.
    """
    from PIL import ImageDraw
    img = Image.new("RGBA", (px, px), (0, 0, 0, 0))
    ss = 4                                    # supersample; glyphs are thin

    # Reproduce the vector drawable's own group transform exactly: scale about
    # the glyph centre, then translate into the 108-unit viewport, then map
    # that viewport onto the pixel size. A preview drawn any other way would
    # show a layout the device will not produce.
    def place(x, y):
        gx = (x - GLYPH_PIVOT) * GLYPH_SCALE + GLYPH_PIVOT + GLYPH_TRANSLATE
        gy = (y - GLYPH_PIVOT) * GLYPH_SCALE + GLYPH_PIVOT + GLYPH_TRANSLATE
        k = px * ss / float(ADAPTIVE_SIZE)
        return gx * k, gy * k

    big = Image.new("L", (px * ss, px * ss), 0)

    rgb = tuple(int(colour_hex[i:i + 2], 16) for i in (3, 5, 7))

    for sub in _subpaths(path_data):
        pts = _flatten(sub)
        if len(pts) >= 3:
            # evenOdd: XOR each subpath so the counters punch through.
            layer = Image.new("L", big.size, 0)
            ImageDraw.Draw(layer).polygon(
                [place(x, y) for x, y in pts], fill=255)
            big = Image.fromarray(
                (np.asarray(big).astype(np.int16) ^ np.asarray(layer).astype(np.int16)
                 ).astype(np.uint8))

    mask = big.resize((px, px), Image.LANCZOS)
    img.paste(Image.new("RGBA", (px, px), rgb + (255,)), (0, 0), mask)
    return img


def _subpaths(data):
    out, cur = [], ""
    for tok in re.findall(r"[MmLlAaCcZzHhVv][^MmLlAaCcZzHhVv]*", data):
        if tok[0] in "Mm" and cur:
            out.append(cur)
            cur = tok
        else:
            cur += tok
    if cur:
        out.append(cur)
    return out


def _nums(s):
    return [float(n) for n in re.findall(r"-?\d*\.?\d+(?:e-?\d+)?", s)]


def _flatten(sub, steps=24):
    """Path to a polygon. Arcs and cubics are sampled, not solved exactly."""
    pts, cx, cy, start = [], 0.0, 0.0, None
    for tok in re.findall(r"[MmLlAaCcZzHhVv][^MmLlAaCcZzHhVv]*", sub):
        cmd, n = tok[0], _nums(tok[1:])
        if cmd == "M":
            for i in range(0, len(n) - 1, 2):
                cx, cy = n[i], n[i + 1]
                pts.append((cx, cy))
            start = pts[0] if pts else None
        elif cmd == "L":
            for i in range(0, len(n) - 1, 2):
                cx, cy = n[i], n[i + 1]
                pts.append((cx, cy))
        elif cmd == "H":
            for v in n:
                cx = v
                pts.append((cx, cy))
        elif cmd == "V":
            for v in n:
                cy = v
                pts.append((cx, cy))
        elif cmd == "C":
            for i in range(0, len(n) - 5, 6):
                x1, y1, x2, y2, x, y = n[i:i + 6]
                for k in range(1, steps + 1):
                    t = k / steps
                    u = 1 - t
                    pts.append((
                        u**3 * cx + 3 * u * u * t * x1 + 3 * u * t * t * x2 + t**3 * x,
                        u**3 * cy + 3 * u * u * t * y1 + 3 * u * t * t * y2 + t**3 * y))
                cx, cy = x, y
        elif cmd == "A":
            for i in range(0, len(n) - 6, 7):
                rx, ry, _, _, sweep, x, y = n[i:i + 7]
                pts.extend(_arc(cx, cy, rx, ry, sweep, x, y, steps))
                cx, cy = x, y
        elif cmd == "Z" and start:
            pts.append(start)
    return pts


def _arc(x0, y0, rx, ry, sweep, x1, y1, steps):
    """Sample an SVG arc. Only the circular, non-rotated case the glyphs use."""
    if rx <= 0 or ry <= 0:
        return [(x1, y1)]
    mx, my = (x0 + x1) / 2.0, (y0 + y1) / 2.0
    dx, dy = (x1 - x0) / 2.0, (y1 - y0) / 2.0
    d2 = (dx / rx) ** 2 + (dy / ry) ** 2
    if d2 > 1:                                # radii too small; scale them up
        k = math.sqrt(d2)
        rx, ry = rx * k, ry * k
        d2 = 1.0
    c = math.sqrt(max(0.0, 1.0 / d2 - 1.0))
    sign = 1.0 if sweep else -1.0
    ccx = mx + sign * c * rx * (dy / ry)
    ccy = my - sign * c * ry * (dx / rx)
    a0 = math.atan2((y0 - ccy) / ry, (x0 - ccx) / rx)
    a1 = math.atan2((y1 - ccy) / ry, (x1 - ccx) / rx)
    if sweep and a1 < a0:
        a1 += 2 * math.pi
    if not sweep and a1 > a0:
        a1 -= 2 * math.pi
    return [(ccx + rx * math.cos(a0 + (a1 - a0) * k / steps),
             ccy + ry * math.sin(a0 + (a1 - a0) * k / steps))
            for k in range(1, steps + 1)]


if __name__ == "__main__":
    main()
